# -*- coding: utf-8 -*-
"""detectar_fraudes_cartao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YADdQP2us9SgMKulWqAF4siYAVH18jXq
"""

# 📦 Importar bibliotecas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

# 📥 Carregar dados
url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
df = pd.read_csv(url)

# 👀 Ver dados
print(df.head())
print(df['Class'].value_counts())

# 🎯 Separar features e target
X = df.drop('Class', axis=1)
y = df['Class']

# ✂️ Dividir treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 🤖 Treinar modelo (Regressão Linear)
model = LinearRegression()
model.fit(X_train, y_train)

# 🔮 Fazer previsões
y_pred = model.predict(X_test)

# 🔄 Converter previsões para 0 ou 1 (threshold 0.5)
y_pred_class = (y_pred > 0.5).astype(int)

# 📊 Avaliar acurácia
accuracy = accuracy_score(y_test, y_pred_class)
print(f"Acurácia: {accuracy:.4f}")

"""O primeiro teste foi utilizando a Regressão Linear. Agora vamos utilizar Regressão Logística"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Modelo melhor
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Previsões
y_pred = model.predict(X_test)

# Avaliação completa
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório:")
print(classification_report(y_test, y_pred))

A seguir vamos ver como fazer Balanceamento (SMOTE)

# ⚖️ Aplicar SMOTE SOMENTE no treino
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Antes do SMOTE:")
print(y_train.value_counts())

print("\nDepois do SMOTE:")
print(pd.Series(y_train_res).value_counts())

# 🤖 Treinar modelo
model = LogisticRegression(max_iter=1000)
model.fit(X_train_res, y_train_res)

# 🔮 Previsões
y_pred = model.predict(X_test)

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))

print("\nMatriz de confusão:")

"""Agora vamos usar RandomForest. Os parâmetros foram reduzidos devido ao tamanho do dataset"""

from sklearn.ensemble import RandomForestClassifier
# 🌲 Modelo Random Forest
model = RandomForestClassifier(
    n_estimators=30,
    max_depth=8,
    max_features='sqrt',
    n_jobs=-1,
    random_state=42
)

# 🤖 Treinar
model.fit(X_train, y_train)

# 🔮 Previsões
y_pred = model.predict(X_test)

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))

print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de classificação:")
print(classification_report(y_test, y_pred))

"""Agora vamos ver como usar XGBoost com base nos dados originais"""

!pip install xgboost
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from xgboost import XGBClassifier

# ⚖️ Calcular peso da classe (IMPORTANTÍSSIMO)
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# 🚀 Modelo XGBoost
model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,  # 🔥 chave para dados desbalanceados
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

# 🤖 Treinar
model.fit(X_train, y_train)

# 🔮 Previsões
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de classificação:")
print(classification_report(y_test, y_pred))